# Generated by Django 2.2.11 on 2022-12-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221205_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='enter category/tag here', max_length=20),
        ),
    ]
